repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
        files: ^pyproject\.toml$
      - id: check-yaml
        files: ^\.github/|^\.pre-commit-config\.yaml$
      - id: trailing-whitespace
        exclude: '\.(bst|bib|sty|tex)$'
      - id: end-of-file-fixer
        exclude: '\.(bst|bib|sty|tex)$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
