#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(ggplot2)
  library(grid)
  library(gridExtra)
  library(jsonlite)
  library(scales)
})

`%||%` <- function(x, y) if (length(x) == 0 || is.null(x) || is.na(x)) y else x

args_all <- commandArgs(trailingOnly = FALSE)
file_arg <- args_all[grep("^--file=", args_all)]
script_dir <- if (length(file_arg)) dirname(normalizePath(sub("^--file=", "", file_arg[1]), mustWork = FALSE)) else getwd()
ROOT <- normalizePath(file.path(script_dir, ".."), mustWork = FALSE)
if (!file.exists(file.path(ROOT, "article", "dpmm", "main_mdpi.tex"))) {
  ROOT <- "/home/zeyufu/Desktop/labs/active/PanODE-DPMM"
}
source(file.path(ROOT, "refined_figures", "figure_standard.R"))

OUT <- file.path(ROOT, "article", "dpmm", "figures", "submission")
PANEL_OUT <- file.path(OUT, "tikz")
dir.create(PANEL_OUT, recursive = TRUE, showWarnings = FALSE)

`%||%` <- function(x, y) if (length(x) == 0 || is.null(x) || is.na(x)) y else x

COLORS <- c("Pure-AE" = "#4E79A7", "DPMM-Base" = "#F28E2B", "DPMM-FM" = "#5C6BC0")
FILL_GRAY <- "#F7F8FA"
INK <- "#222222"
LETTERS <- LETTERS[1:4]

core_path <- file.path(ROOT, "experiments", "results", "dpmm_fm_core", "summary.csv")
sens_path <- file.path(ROOT, "experiments", "results", "dpmm_fm_sensitivity_core", "summary.csv")
ext_path <- file.path(ROOT, "article", "dpmm", "data", "per_variant_external_summary.csv")

read_core <- function() read.csv(core_path, check.names = FALSE)
read_sens <- function() read.csv(sens_path, check.names = FALSE)
read_external <- function() read.csv(ext_path, check.names = FALSE)

wrap_text <- function(x, width = 34) paste(strwrap(x, width = width), collapse = "\n")
short_label <- function(x, width = 24) vapply(x, wrap_text, character(1), width = width)

panel_base <- function(title, tag) {
  ggplot() +
    labs(title = title, tag = tag) +
    theme(plot.title = element_text(face = "bold"), plot.tag = element_text(face = "bold"))
}

text_panel <- function(title, tag, lines, color = "#2F4B7C") {
  y <- seq(0.78, 0.22, length.out = length(lines))
  df <- data.frame(x = 0.08, y = y, label = lines)
  panel_base(title, tag) +
    annotate("rect", xmin = 0.02, xmax = 0.98, ymin = 0.06, ymax = 0.92,
             fill = FILL_GRAY, colour = color, linewidth = 0.45) +
    geom_text(data = df, aes(x, y, label = label), hjust = 0, vjust = 1,
              size = 2.7, lineheight = 1.05, colour = INK) +
    coord_cartesian(xlim = c(0, 1), ylim = c(0, 1), expand = FALSE) +
    theme_void(base_size = STD_BASE_SIZE) +
    theme(plot.title = element_text(size = STD_BASE_SIZE + 1, face = "bold", hjust = 0),
          plot.tag = element_text(size = STD_BASE_SIZE + 2, face = "bold"),
          plot.margin = margin(2, 2, 2, 2))
}

bar_panel <- function(df, x, y, fill = NULL, title, tag, ylabel = "", xlabel = NULL,
                      rotate = 25, limits = NULL) {
  aes_base <- aes(x = .data[[x]], y = .data[[y]])
  p <- ggplot(df, aes_base) + labs(title = title, tag = tag, x = xlabel, y = ylabel)
  if (!is.null(fill)) {
    p <- p + geom_col(aes(fill = .data[[fill]]), width = 0.68, colour = "white", linewidth = 0.25) +
      scale_fill_manual(values = COLORS, guide = guide_legend(title = NULL))
  } else {
    p <- p + geom_col(width = 0.68, fill = "#4E79A7", colour = "white", linewidth = 0.25)
  }
  if (!is.null(limits)) p <- p + coord_cartesian(ylim = limits)
  p + std_theme() +
    theme(plot.title = element_text(face = "bold", hjust = 0),
          axis.text.x = element_text(angle = rotate, hjust = 1),
          legend.position = if (is.null(fill)) "none" else "top",
          panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())
}

save_panel <- function(p, fig, tag, slug, w = 2.35, h = 1.70) {
  f <- file.path(PANEL_OUT, sprintf("F%02d%s_%s.tex", fig, tag, slug))
  fitted <- save_tikz_std(p, f, plot_w_in = w, plot_h_in = h, sanitize = TRUE)
  data.frame(figure = sprintf("F%02d", fig), panel = tag, file = f,
             plot_w_in = w, plot_h_in = h, canvas_w_in = fitted$w_in,
             canvas_h_in = fitted$h_in, stringsAsFactors = FALSE)
}

write_wrapper <- function(fig, slug, composed_file, source_note) {
  base <- sprintf("F%02d_%s", fig, slug)
  wrapper <- file.path(OUT, paste0(base, ".tex"))
  rel <- file.path("figures", "submission", "tikz", basename(composed_file))
  body <- sprintf("%% Auto-generated by refined_figures/build_std_figures.R\n%% Source: %s\n\\resizebox{\\textwidth}{!}{%%\n\\input{%s}%%\n}\n", source_note, rel)
  writeLines(body, wrapper)
  wrapper
}

save_figure <- function(panels, fig, slug, source_note, ncol = 2, w = 2.35, h = 1.70) {
  f <- file.path(PANEL_OUT, sprintf("F%02d_%s_composed.tex", fig, slug))
  composed <- save_tikz_composed(panels, f, ncol = ncol, plot_w_in = w, plot_h_in = h,
                                 sanitize = TRUE)
  write_wrapper(fig, slug, f, source_note)
  panel_tags <- LETTERS[seq_along(panels)]
  data.frame(figure = sprintf("F%02d", fig), panel = panel_tags, file = f,
             plot_w_in = w, plot_h_in = h,
             canvas_w_in = vapply(composed$fits, function(x) x$w_in, numeric(1)),
             canvas_h_in = vapply(composed$fits, function(x) x$h_in, numeric(1)),
             composed_w_in = composed$w_in, composed_h_in = composed$h_in,
             stringsAsFactors = FALSE)
}

mean_by_model <- function(d) aggregate(d[, sapply(d, is.numeric), drop = FALSE], list(model = d$model), mean, na.rm = TRUE)

fig1 <- function() {
  panels <- list(
    text_panel("Shared autoencoder", "A", c("3,000 HVGs -> encoder [256,128]", "10-D latent representation", "reconstruction objective shared", "across all three variants"), COLORS[["Pure-AE"]]),
    text_panel("Adaptive DPMM prior", "B", c("90% reconstruction warmup", "Bayesian mixture refit", "every 10 epochs", "cluster count inferred online"), COLORS[["DPMM-Base"]]),
    text_panel("Conditional flow refinement", "C", c("transport toward DPMM centers", "flow weight lambda_FM = 0.1", "noise scale = 0.5", "projection-fidelity hypothesis"), COLORS[["DPMM-FM"]]),
    text_panel("Pre-specified operating points", "D", c("Pure-AE: label concordance", "DPMM-Base: compact geometry", "DPMM-FM: projection fidelity", "No universal-best assumption"), "#2E7D32")
  )
  dims <- save_figure(panels, 1, "architecture", "models/dpmm_base.py; models/dpmm_flow_matching.py")
  dims
}

fig2 <- function() {
  d <- mean_by_model(read_core())
  order <- intersect(c("Pure-AE", "DPMM-Base", "DPMM-FM"), d$model)
  d$model <- factor(d$model, levels = order)
  q <- d[d$model %in% order, ]
  lab <- rbind(data.frame(model = q$model, metric = "NMI", score = q$NMI),
               data.frame(model = q$model, metric = "ARI", score = q$ARI))
  fid <- rbind(data.frame(model = q$model, metric = "DRE-UMAP", score = q$DRE_umap_overall_quality),
               data.frame(model = q$model, metric = "DRE-tSNE", score = q$DRE_tsne_overall_quality))
  p1 <- ggplot(lab, aes(model, score, fill = metric)) + geom_col(position = position_dodge(width = .72), width = .64, colour = "white", linewidth = .2) +
    scale_fill_manual(values = c("NMI" = "#4E79A7", "ARI" = "#59A14F")) + labs(title = "Label concordance", tag = "A", x = NULL, y = "score") + std_theme() + theme(legend.position = "top", axis.text.x = element_text(angle = 20, hjust = 1), plot.title = element_text(face = "bold", hjust = 0), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())
  p2 <- bar_panel(q, "model", "ASW", "model", "Cluster compactness", "B", "ASW", rotate = 20)
  p3 <- ggplot(fid, aes(model, score, fill = metric)) + geom_col(position = position_dodge(width = .72), width = .64, colour = "white", linewidth = .2) +
    scale_fill_manual(values = c("DRE-UMAP" = "#5C6BC0", "DRE-tSNE" = "#9C755F")) + labs(title = "Projection fidelity", tag = "C", x = NULL, y = "quality") + std_theme() + theme(legend.position = "top", axis.text.x = element_text(angle = 20, hjust = 1), plot.title = element_text(face = "bold", hjust = 0), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())
  p4 <- ggplot(q, aes(NMI, ASW, colour = model, label = model)) + geom_point(size = 2.8) + geom_text(nudge_y = .02, size = 2.4, show.legend = FALSE) + scale_colour_manual(values = COLORS) + labs(title = "Pareto, not dominance", tag = "D", x = "NMI", y = "ASW") + std_theme() + theme(legend.position = "none", plot.title = element_text(face = "bold", hjust = 0))
  dims <- save_figure(list(p1, p2, p3, p4), 2, "tradeoff", "experiments/results/dpmm_fm_core/summary.csv")
  dims
}

fig3 <- function() {
  metrics <- c("NMI", "ARI", "ASW", "DAV")
  wins <- c(2, 4, 12, 12); losses <- c(10, 8, 0, 0)
  pvals <- c(.999, .924, 2.44e-4, 2.44e-4); delta <- c(-.639, -.431, 1, 1)
  d1 <- rbind(data.frame(metric = metrics, outcome = "wins", n = wins), data.frame(metric = metrics, outcome = "losses", n = losses))
  p1 <- ggplot(d1, aes(metric, n, fill = outcome)) + geom_col(position = position_dodge(width = .72), width = .64, colour = "white", linewidth = .2) + scale_fill_manual(values = c("wins" = "#59A14F", "losses" = "#C44E52")) + labs(title = "Directional outcomes", tag = "A", x = NULL, y = "datasets") + std_theme() + theme(legend.position = "top", plot.title = element_text(face = "bold", hjust = 0), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())
  d2 <- data.frame(metric = metrics, score = -log10(pvals))
  p2 <- ggplot(d2, aes(metric, score)) + geom_col(fill = "#4E79A7", colour = "white", linewidth = .2, width = .68) + geom_hline(yintercept = -log10(.05), linetype = "dashed", colour = "#C44E52", linewidth = .35) + labs(title = "Wilcoxon evidence", tag = "B", x = NULL, y = "-log10(p)") + std_theme() + theme(plot.title = element_text(face = "bold", hjust = 0), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())
  d3 <- data.frame(metric = metrics, delta = delta, direction = ifelse(delta < 0, "concordance cost", "geometry gain"))
  p3 <- ggplot(d3, aes(metric, delta, fill = direction)) + geom_col(width = .68, colour = "white", linewidth = .2) + geom_hline(yintercept = 0, linewidth = .3) + scale_fill_manual(values = c("concordance cost" = "#C44E52", "geometry gain" = "#59A14F")) + labs(title = "Cliff's delta", tag = "C", x = NULL, y = "effect") + std_theme() + theme(legend.position = "top", plot.title = element_text(face = "bold", hjust = 0), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())
  p4 <- text_panel("Interpretation", "D", c("ASW and DAV: 12/12 wins", "p = 2.44e-4; delta = 1.0", "NMI/ARI losses are directional", "but not signed-rank significant"), "#2F4B7C")
  dims <- save_figure(list(p1, p2, p3, p4), 3, "statistics", "article/dpmm/tables/wilcoxon_core.tex")
  dims
}

fig4 <- function() {
  d <- read_sens()
  specs <- list(c("flow_weight", "NMI", "Flow weight: NMI"), c("flow_weight", "DRE_umap_overall_quality", "Flow weight: DRE-UMAP"), c("flow_noise_scale", "ARI", "Noise scale: ARI"), c("flow_noise_scale", "LSE_overall_quality", "Noise scale: LSE"))
  panels <- list()
  for (i in seq_along(specs)) {
    sw <- specs[[i]][1]; m <- specs[[i]][2]; ttl <- specs[[i]][3]
    sub <- d[d$Sweep == sw, ]
    g_mean <- aggregate(sub[[m]], list(SweepVal = sub$SweepVal), mean, na.rm = TRUE)
    g_sd <- aggregate(sub[[m]], list(SweepVal = sub$SweepVal), sd, na.rm = TRUE)
    names(g_mean)[2] <- "mean"; names(g_sd)[2] <- "sd"
    g <- merge(g_mean, g_sd, by = "SweepVal", all = TRUE)
    g$sd[is.na(g$sd)] <- 0
    panels[[i]] <- ggplot(g, aes(SweepVal, mean)) + geom_line(colour = COLORS[["DPMM-FM"]], linewidth = .45) + geom_point(colour = COLORS[["DPMM-FM"]], size = 1.6) + geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = .02, colour = COLORS[["DPMM-FM"]], linewidth = .3) + labs(title = ttl, tag = LETTERS[i], x = gsub("_", " ", sw), y = sub("_.*", "", m)) + std_theme() + theme(plot.title = element_text(face = "bold", hjust = 0), panel.grid.minor = element_blank())
  }
  dims <- save_figure(panels, 4, "sensitivity", "experiments/results/dpmm_fm_sensitivity_core/summary.csv")
  dims
}

fig5 <- function() {
  h <- fromJSON(file.path(ROOT, "benchmarks", "training_dynamics_results", "DPMM-Base_setty_history.json"))
  mk_line <- function(values, title, tag, ylab, col, x = seq_along(values)) {
    ggplot(data.frame(epoch = x, value = values), aes(epoch, value)) + geom_line(colour = col, linewidth = .35) + labs(title = title, tag = tag, x = "epoch", y = ylab) + std_theme() + theme(plot.title = element_text(face = "bold", hjust = 0), panel.grid.minor = element_blank())
  }
  p1 <- mk_line(h$train_loss, "Total loss", "A", "loss", "#4E79A7")
  p2 <- mk_line(h$recon_loss, "Reconstruction loss", "B", "loss", "#59A14F")
  p3 <- mk_line(h$dpmm_loss, "DPMM loss after warmup", "C", "loss", "#F28E2B") + geom_vline(xintercept = 540, linetype = "dashed", colour = "#333333", linewidth = .3)
  snaps <- as.data.frame(h$snapshots)
  long <- rbind(data.frame(epoch = snaps$epoch, metric = "NMI", value = snaps$NMI), data.frame(epoch = snaps$epoch, metric = "ARI", value = snaps$ARI), data.frame(epoch = snaps$epoch, metric = "ASW", value = snaps$ASW))
  p4 <- ggplot(long, aes(epoch, value, colour = metric)) + geom_line(linewidth = .35) + scale_colour_manual(values = c("NMI" = "#4E79A7", "ARI" = "#59A14F", "ASW" = "#F28E2B")) + labs(title = "Snapshot metrics", tag = "D", x = "epoch", y = "score") + std_theme() + theme(legend.position = "top", plot.title = element_text(face = "bold", hjust = 0), panel.grid.minor = element_blank())
  dims <- save_figure(list(p1, p2, p3, p4), 5, "training", "benchmarks/training_dynamics_results/DPMM-Base_setty_history.json")
  dims
}

read_npy_array <- function(path) {
  con <- file(path, "rb"); on.exit(close(con))
  magic <- readBin(con, "raw", 6)
  if (!identical(as.integer(magic), as.integer(charToRaw("\x93NUMPY")))) stop("Not an NPY file: ", path)
  version <- readBin(con, "integer", 2, size = 1, signed = FALSE)
  hlen <- if (version[1] <= 1) readBin(con, "integer", 1, size = 2, endian = "little", signed = FALSE) else readBin(con, "integer", 1, size = 4, endian = "little", signed = FALSE)
  header <- rawToChar(readBin(con, "raw", hlen))
  descr <- sub(".*'descr': '([^']+)'.*", "\\1", header)
  shape_txt <- sub(".*'shape': \\(([^)]*)\\).*", "\\1", header)
  shape <- as.integer(gsub("[^0-9,]", "", strsplit(shape_txt, ",")[[1]]))
  shape <- shape[!is.na(shape)]
  n <- prod(shape)
  if (descr == "<f4") values <- readBin(con, "numeric", n, size = 4, endian = "little")
  else if (descr == "<f8") values <- readBin(con, "numeric", n, size = 8, endian = "little")
  else if (descr == "<i4") values <- readBin(con, "integer", n, size = 4, endian = "little", signed = TRUE)
  else stop("Unsupported NPY dtype ", descr, " in ", path)
  if (length(shape) == 2) matrix(values, nrow = shape[1], ncol = shape[2], byrow = TRUE) else values
}

read_npz_member <- function(npz_path, member) {
  td <- tempfile("npz_"); dir.create(td)
  on.exit(unlink(td, recursive = TRUE), add = TRUE)
  utils::unzip(npz_path, files = member, exdir = td)
  read_npy_array(file.path(td, member))
}

fig6 <- function() {
  umap_panel <- function(ds, tag) {
    pth <- file.path(ROOT, "benchmarks", "biological_validation", "results", sprintf("DPMM-Base_%s_umap_data.npz", ds))
    emb <- read_npz_member(pth, "umap_emb.npy")
    labels <- factor(read_npz_member(pth, "labels.npy"))
    df <- data.frame(UMAP1 = emb[, 1], UMAP2 = emb[, 2], label = labels)
    ggplot(df, aes(UMAP1, UMAP2, colour = label)) +
      geom_point(size = .35, alpha = .68, show.legend = FALSE) +
      labs(title = sprintf("%s: saved UMAP", ds), tag = tag, x = NULL, y = NULL) +
      scale_colour_manual(values = hue_pal()(length(levels(labels)))) +
      std_theme() +
      theme(axis.text = element_blank(), axis.ticks = element_blank(),
            plot.title = element_text(face = "bold", hjust = 0),
            panel.grid = element_blank())
  }
  enrich_files <- list.files(file.path(ROOT, "benchmarks", "biological_validation", "results", "DPMM-Base"),
                             pattern = "DPMM-Base_dentate_enrichment_comp.*\\.csv$", full.names = TRUE)
  enrich <- lapply(head(sort(enrich_files), 6), function(p) {
    d <- read.csv(p, check.names = FALSE)
    row <- d[order(d[["Adjusted P-value"]]), ][1, ]
    data.frame(term = substr(as.character(row$Term), 1, 28),
               score = -log10(max(as.numeric(row[["Adjusted P-value"]]), 1e-300)))
  })
  enrich <- do.call(rbind, enrich)
  p4 <- ggplot(enrich, aes(reorder(term, score), score)) + geom_col(fill = "#59A14F", width = .68, colour = "white", linewidth = .2) + coord_flip() + labs(title = "Dentate GO exploration", tag = "D", x = NULL, y = "-log10 adjusted p") + std_theme() + theme(plot.title = element_text(face = "bold", hjust = 0), panel.grid.major.y = element_blank(), panel.grid.minor = element_blank())
  dims <- save_figure(list(umap_panel("setty", "A"), umap_panel("endo", "B"), umap_panel("dentate", "C"), p4), 6, "biological", "benchmarks/biological_validation/results/DPMM-Base_*_umap_data.npz; DPMM-Base/*enrichment*.csv")
  dims
}

fig7 <- function() {
  d <- read_external(); d <- d[d$Model %in% c("DPMM-Base", "Pure-AE"), ]
  d$Model <- factor(d$Model, levels = c("Pure-AE", "DPMM-Base"))
  p1 <- bar_panel(d, "Model", "Significant_all", "Model", "Full-screen significant wins", "A", "tests", rotate = 20)
  p2 <- bar_panel(d, "Model", "Core_significant", "Model", "Core significant wins", "B", "of 44", rotate = 20)
  p3 <- bar_panel(d, "Model", "Core_win_rate", "Model", "Core win rate", "C", "fraction", rotate = 20, limits = c(0, 1))
  p4 <- text_panel("Selection and provenance", "D", c("Statistics: 56 datasets x 18 baselines", "Display: 12 complete core datasets", "11 representative baseline methods", "Primary Wilcoxon export in-repo"), "#2F4B7C")
  dims <- save_figure(list(p1, p2, p3, p4), 7, "external_selection", "article/dpmm/data/per_variant_external_summary.csv; article/dpmm/data/per_variant_external_wilcoxon.csv; PROVENANCE-GAP.md")
  dims
}

fig8 <- function() {
  d <- read_external(); d <- d[order(-d$Core_win_rate), ][seq_len(min(8, nrow(d))), ]
  d$ModelShort <- gsub("Pure-", "P-", gsub("DPMM-", "D-", gsub("Topic-", "T-", d$Model)))
  p1 <- ggplot(d, aes(reorder(Model, Core_win_rate), Core_win_rate)) + geom_col(fill = "#4E79A7", width = .68, colour = "white", linewidth = .2) + coord_flip() + labs(title = "Top summary win rates", tag = "A", x = NULL, y = "core win rate") + std_theme() + theme(plot.title = element_text(face = "bold", hjust = 0), panel.grid.major.y = element_blank(), panel.grid.minor = element_blank())
  p2 <- ggplot(d, aes(Significant_all, Core_significant, label = ModelShort)) + geom_point(size = 2.2, colour = "#355C7D") + geom_text(nudge_y = 1.2, size = 2.1, show.legend = FALSE) + labs(title = "All vs core significant wins", tag = "B", x = "all significant", y = "core significant") + std_theme() + theme(plot.title = element_text(face = "bold", hjust = 0), legend.position = "none", panel.grid.minor = element_blank())
  p3 <- ggplot(head(d, 6), aes(ModelShort, Total_tests)) + geom_col(fill = "#9E9E9E", width = .68, colour = "white", linewidth = .2) + labs(title = "Test-count coverage", tag = "C", x = NULL, y = "tests") + std_theme() + theme(axis.text.x = element_text(angle = 35, hjust = 1), plot.title = element_text(face = "bold", hjust = 0), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())
  p4 <- text_panel("Provenance closed", "D", c("Primary per-variant Wilcoxon in-repo", "DPMM-Base: 407 tests; 176 sig wins", "Core: 31/44 (NMI9 ARI9 ASW7 DAV6)", "Residual: raw score dumps not imported"), "#2F4B7C")
  dims <- save_figure(list(p1, p2, p3, p4), 8, "external_provenance", "article/dpmm/data/per_variant_external_wilcoxon.csv; article/dpmm/PROVENANCE-GAP.md")
  dims
}

parse_table_number <- function(path, model, col_index) {
  lines <- readLines(path, warn = FALSE)
  row <- lines[startsWith(trimws(lines), model)][1]
  if (is.na(row)) stop("Could not find row for ", model, " in ", path)
  row <- gsub("\\\\textbf\\{|\\}", "", row)
  row <- gsub("\\\\\\\\", "", row)
  parts <- strsplit(row, "&", fixed = TRUE)[[1]]
  as.numeric(gsub("[^0-9.]", "", parts[col_index]))
}

fig9 <- function() {
  knn <- file.path(ROOT, "article", "dpmm", "tables", "knn.tex")
  runtime <- file.path(ROOT, "article", "dpmm", "tables", "runtime.tex")
  d <- data.frame(Model = c("Pure-AE", "DPMM-Base"),
                  Accuracy = c(parse_table_number(knn, "Pure-AE", 2), parse_table_number(knn, "DPMM-Base", 2)),
                  F1 = c(parse_table_number(knn, "Pure-AE", 3), parse_table_number(knn, "DPMM-Base", 3)),
                  Time = c(parse_table_number(runtime, "Pure-AE", 2), parse_table_number(runtime, "DPMM-Base", 2)),
                  Params = c(parse_table_number(runtime, "Pure-AE", 5), parse_table_number(runtime, "DPMM-Base", 5)))
  d$Model <- factor(d$Model, levels = c("Pure-AE", "DPMM-Base"))
  p1 <- bar_panel(d, "Model", "Accuracy", "Model", "kNN accuracy", "A", "score", rotate = 20, limits = c(0, .9))
  p2 <- bar_panel(d, "Model", "F1", "Model", "kNN macro-F1", "B", "score", rotate = 20, limits = c(0, .7))
  p3 <- bar_panel(d, "Model", "Time", "Model", "Mean training time", "C", "seconds", rotate = 20)
  p4 <- bar_panel(d, "Model", "Params", "Model", "Parameter count", "D", "parameters", rotate = 20)
  dims <- save_figure(list(p1, p2, p3, p4), 9, "utility_cost", "article/dpmm/tables/knn.tex; article/dpmm/tables/runtime.tex")
  dims
}

fig10 <- function() {
  p1 <- text_panel("Label recovery", "A", c("Choose Pure-AE", "NMI 0.609; ARI 0.406", "kNN accuracy 0.784", "No prior-induced boundary shift"), COLORS[["Pure-AE"]])
  p2 <- text_panel("Compact geometry", "B", c("Choose DPMM-Base", "ASW 0.374; DAV 0.868", "12/12 ASW and DAV wins", "Accept concordance cost"), COLORS[["DPMM-Base"]])
  p3 <- text_panel("Projection fidelity", "C", c("Choose DPMM-FM", "DRE/LSE/DREX operating point", "Flow smooths global manifold", "Not a clustering optimum"), COLORS[["DPMM-FM"]])
  mat <- expand.grid(model = factor(c("Pure-AE", "DPMM-Base", "DPMM-FM"), levels = c("Pure-AE", "DPMM-Base", "DPMM-FM")), objective = factor(c("labels", "geometry", "projection", "classification"), levels = c("labels", "geometry", "projection", "classification")))
  mat$score <- c(3, 1, 0, 1, 3, 2, 1, 2, 3, 3, 1, 0)
  mat$score <- factor(mat$score, levels = 0:3)
  p4 <- ggplot(mat, aes(objective, model, fill = score)) + geom_tile(colour = "white", linewidth = .5) + geom_text(aes(label = score), size = 2.8) + scale_fill_manual(values = c("0" = "#F7FBFF", "1" = "#C6DBEF", "2" = "#6BAED6", "3" = "#2171B5"), drop = FALSE) + labs(title = "Evidence-based suitability", tag = "D", x = NULL, y = NULL) + std_theme() + theme(axis.text.x = element_text(angle = 25, hjust = 1), legend.position = "none", plot.title = element_text(face = "bold", hjust = 0), panel.grid = element_blank())
  dims <- save_figure(list(p1, p2, p3, p4), 10, "decision_map", "article/dpmm/tables/*.tex; experiments/results/dpmm_fm_core/summary.csv")
  dims
}

main <- function() {
  required <- c(core_path, sens_path, ext_path,
                file.path(ROOT, "article", "dpmm", "tables", "knn.tex"),
                file.path(ROOT, "article", "dpmm", "tables", "runtime.tex"),
                file.path(ROOT, "benchmarks", "training_dynamics_results", "DPMM-Base_setty_history.json"))
  missing <- required[!file.exists(required)]
  if (length(missing)) stop("Missing required saved export(s): ", paste(missing, collapse = ", "))
  dims <- do.call(rbind, list(fig1(), fig2(), fig3(), fig4(), fig5(), fig6(), fig7(), fig8(), fig9(), fig10()))
  write.csv(dims, file.path(OUT, "std_figure_dimensions.csv"), row.names = FALSE)
  message("Built 10 tikz-wrapper figures in ", OUT)
  print(dims[, c("figure", "panel", "plot_w_in", "plot_h_in", "canvas_w_in", "canvas_h_in")], row.names = FALSE)
}

main()
