"""Refined Figure 11 — DPMM posterior diagnostics.

Six-panel figure showing DPMM-specific partition/uncertainty metrics for
the proposed DPMM-MoCo-AE model vs Pure-AE baseline across datasets:
  (a) Occupied cluster count (K_occ)
  (b) Mixing weight Gini coefficient
  (c) Occupancy entropy (H_occ)
  (d) Singleton rate (SIR_1)
  (e) Neighborhood Fragmentation Index (NFI)
  (f) Co-clustering sharpness (PCS)

Data source:
  experiments/results/dpmm_diagnostics/dpmm_metrics.csv
  (generated by scripts/compute_dpmm_diagnostics.py)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.visualization import (
    apply_style,
    style_axes,
    save_with_vcd,
    bind_figure_region,
)
from refined_figures.dpmm_shared import (
    require_dpmm,
    method_color,
    method_short_name,
)

DPI = 300
_DIAGNOSTICS_CSV = ROOT / "experiments" / "results" / "dpmm_diagnostics" / "dpmm_metrics.csv"

_MODEL_ORDER = [
    "Pure-AE",
    "DPMM-Contrastive",
]

_PANELS = [
    ("K_occ", "(a) Occupied Clusters",     True),
    ("Gini",  "(b) Weight Gini",           False),
    ("H_occ", "(c) Occupancy Entropy",     True),
    ("SIR_1", "(d) Singleton Rate",        False),
    ("NFI",   "(e) Neighborhood Frag.",    False),
    ("PCS",   "(f) Co-cluster Sharpness",  True),
]


def _draw_grouped_bar(ax, df, metric_col, label, model_order, higher_is_better):
    datasets = sorted(df["dataset"].unique())
    n_ds = len(datasets)
    n_mod = len(model_order)
    bar_w = 0.7 / n_mod
    x = np.arange(n_ds)

    for mi, model in enumerate(model_order):
        vals = []
        for ds in datasets:
            sub = df[(df["model"] == model) & (df["dataset"] == ds)]
            vals.append(float(sub[metric_col].iloc[0]) if len(sub) > 0 else 0.0)
        offset = (mi - (n_mod - 1) / 2) * bar_w
        ax.bar(x + offset, vals, width=bar_w * 0.88,
               color=method_color(model), edgecolor="#666666", linewidth=0.4,
               alpha=0.82, label=method_short_name(model))

    ax.set_xticks(x)
    ax.set_xticklabels(datasets, fontsize=7, rotation=30, ha="right")
    ax.set_title(label, fontsize=10, fontweight="bold", loc="left", pad=4)
    ax.tick_params(labelsize=7)
    ax.grid(axis="y", alpha=0.15, lw=0.4)

    # Add direction arrow in title area
    arrow = " (higher=better)" if higher_is_better else " (lower=better)"
    ax.annotate(arrow, xy=(1.0, 1.02), xycoords="axes fraction",
                fontsize=6, color="#888888", ha="right", va="bottom")


def generate(series, out_dir):
    series = require_dpmm(series)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    apply_style()

    if not _DIAGNOSTICS_CSV.exists():
        print("  SKIP Fig 11: run scripts/compute_dpmm_diagnostics.py first")
        return

    df = pd.read_csv(_DIAGNOSTICS_CSV)

    fig = plt.figure(figsize=(17.0, 10.5))
    root = bind_figure_region(fig, (0.06, 0.06, 0.95, 0.94))
    grid = root.grid(2, 3, wgap=0.07, hgap=0.16)

    for idx, (col, label, hib) in enumerate(_PANELS):
        row, col_i = divmod(idx, 3)
        ax = grid[row][col_i].add_axes(fig)
        style_axes(ax, kind="bar")
        _draw_grouped_bar(ax, df, col, label, _MODEL_ORDER, hib)
        if idx == 0:
            ax.legend(fontsize=6.5, frameon=False, loc="upper right",
                      ncol=2, handlelength=1.0, columnspacing=0.5)

    out_path = out_dir / f"Fig11_dpmm_diagnostics_{series}.png"
    save_with_vcd(fig, out_path, dpi=DPI, close=True)
    print(f"  ok {out_path.name}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--series", default="dpmm", choices=["dpmm"])
    parser.add_argument("--output-dir", default=None)
    args = parser.parse_args()
    out = Path(args.output_dir) if args.output_dir else ROOT / "refined_figures" / "output" / "dpmm"
    generate(args.series, out)
